name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Build all
      run: dotnet build --configuration Release
    
    ############ Core ############
    
    - name: Core tests
      run: > 
        dotnet test "tests/OrleanSpaces.Tests/OrleanSpaces.Tests.csproj" --configuration Release --no-build -v:normal 
        -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --blame-hang-timeout 5m --blame-hang-dump-type full

    - name: Core tests coverage
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: core_badge
      with:
        label: coverage
        color: brightgreen
        path: tests/OrleanSpaces.Tests/TestResults/coverage.opencover.xml
        gist-filename: orleanspaces-core.json
        gist-id: f1e76e073c791df73243a7f113a7e37f
        gist-auth-token: ${{ secrets.GIST_TOKEN }}
        
    ############ Analyzers ############
  
    - name: Analyzers tests
      run: > 
        dotnet test "tests/OrleanSpaces.Analyzers.Tests/OrleanSpaces.Analyzers.Tests.csproj" --configuration Release --no-build -v:normal 
        -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --blame-hang-timeout 5m --blame-hang-dump-type full
        -p:Exclude=[OrleanSpaces]* # removing all types (*) from the assembly (OrleanSpaces) from code coverage, as it is used only as a reference source for the analyzer project.

    - name: Analyzers tests coverage
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: analyzers_badge
      with:
        label: coverage
        color: brightgreen
        path: tests/OrleanSpaces.Analyzers.Tests/TestResults/coverage.opencover.xml
        gist-filename: orleanspaces-analyzers.json
        gist-id: f1e76e073c791df73243a7f113a7e37f
        gist-auth-token: ${{ secrets.GIST_TOKEN }}

     #######################
