name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build all
      run: dotnet build --configuration Release
    
    ############ Core ############
    
    - name: Core tests
      run: dotnet test "tests/OrleanSpaces.Tests/OrleanSpaces.Tests.csproj" --configuration Release --no-build -v:normal -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover

    - name: Core tests coverage
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: core_badge
      with:
        label: Coverage
        color: brightgreen
        path: tests/OrleanSpaces.Tests/TestResults/coverage.opencover.xml
        gist-filename: osa-core-cov.json
        gist-id: ba8ac624da19bbc52e71d9855d47ad85
        gist-auth-token: ${{ secrets.GIST_TOKEN }}
        
    ############ Analyzers ############
  
    - name: Analyzers tests
      run: dotnet test "tests/OrleanSpaces.Analyzers.Tests/OrleanSpaces.Analyzers.Tests.csproj" --configuration Release --no-build -v:normal -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover

    - name: Analyzers tests coverage
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: analyzers_badge
      with:
        label: Coverage
        color: brightgreen
        path: tests/OrleanSpaces.Analyzers.Tests/TestResults/coverage.opencover.xml
        gist-filename: osa-analyzers-cov.json
        gist-id: 8888a48765d5d508f575e955a06f1763
        gist-auth-token: ${{ secrets.GIST_TOKEN }}

     #######################
