name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build all
      run: dotnet build --configuration Release
      
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v2
    
    - name: Main tests
      run: dotnet test "tests/OrleanSpaces.Tests/OrleanSpaces.Tests.csproj" --configuration Release --no-build --logger "trx;LogFileName=main.trx" || true

    - name: Analyzer tests
      run: dotnet test "tests/OrleanSpaces.Analyzers.Tests/OrleanSpaces.Analyzers.Tests.csproj" --configuration Release --no-build --logger "trx;LogFileName=analyzers.trx" || true

    - name: Test reports
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test reports
        path: "*.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
