name: Publish

on:
  workflow_dispatch:
    inputs:
      project_name:
        type: choice
        description: Project name
        options:
        - 'OrleanSpaces'
        - 'OrleanSpaces.Analyzers'
      nuget_version:
        type: string
        description: NuGet version
        
permissions:
  contents: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: Pack
      working-directory: src/${{ inputs.project_name }}
      run: dotnet pack --configuration Release --no-build -p:Version=${{ inputs.nuget_version }}
    - name: Push
      working-directory: src/${{ inputs.project_name }}/bin/Release
      run: |
        dotnet nuget push ${{ inputs.project_name }}.*.nupkg --skip-duplicate -k ${{ secrets.ORLEANSPACES_NUGET_KEY }} -s https://api.nuget.org/v3/index.json
